[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/bookworm-aarch64-unknown-linux-gnu:latest"
pre-build = [
  "apt-get update",
  "apt-get install -y --no-install-recommends \
    libwebkit2gtk-4.1-dev:arm64 \
    libgtk-3-dev:arm64 \
    libxdo-dev:arm64 \
    libssl-dev:arm64 \
    libayatana-appindicator3-dev:arm64 \
    librsvg2-dev:arm64 \
    libsoup-3.0-dev:arm64 \
    libjavascriptcoregtk-4.1-dev:arm64"
]