[target.aarch64-unknown-linux-gnu]
pre-build = [
  "apt-get update",
  "apt-get install -y --no-install-recommends libwebkit2gtk-4.1-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev libssl-dev libxdo-dev pkg-config curl wget file xz-utils"
]
