[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[env]
PKG_CONFIG_ALLOW_CROSS = "1"

[target.aarch64-unknown-linux-gnu.env]
PKG_CONFIG = "aarch64-linux-gnu-pkg-config"
PKG_CONFIG_PATH = "/usr/lib/aarch64-linux-gnu/pkgconfig:/usr/share/pkgconfig"
PKG_CONFIG_LIBDIR = "/usr/lib/aarch64-linux-gnu/pkgconfig:/usr/share/pkgconfig"
PKG_CONFIG_SYSROOT_DIR = "/usr/aarch64-linux-gnu"
CC = "aarch64-linux-gnu-gcc"
CXX = "aarch64-linux-gnu-g++"
AR = "aarch64-linux-gnu-ar"
STRIP = "aarch64-linux-gnu-strip"
