name: "Build and Publish"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number for this release"
        required: true
        default: "0.1.0"
      prerelease:
        description: "Is this a prerelease?"
        type: boolean
        default: false

jobs:
  publish-tauri:
    permissions:
      contents: write
      packages: write
    env:
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_MAX_CONNECTIONS: ${{ secrets.POSTGRES_MAX_CONNECTIONS || 5 }}
      VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Add ARM64 Rust target
        run: rustup target add aarch64-unknown-linux-gnu

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri
          cache-on-failure: true

      - name: Install Tauri dependencies for Debian
        run: |
          sudo rm -f /etc/apt/sources.list.d/* /etc/apt/sources.list /etc/apt/apt-mirrors.txt
          . /etc/os-release
          CODENAME=${UBUNTU_CODENAME:-$(lsb_release -sc)}
          sudo tee /etc/apt/sources.list.d/ubuntu-amd64.list >/dev/null <<EOF
          deb [arch=amd64] http://archive.ubuntu.com/ubuntu $CODENAME main restricted universe multiverse
          deb [arch=amd64] http://archive.ubuntu.com/ubuntu $CODENAME-updates main restricted universe multiverse
          deb [arch=amd64] http://archive.ubuntu.com/ubuntu $CODENAME-backports main restricted universe multiverse
          deb [arch=amd64] http://security.ubuntu.com/ubuntu $CODENAME-security main restricted universe multiverse
          EOF
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            libgtk-3-dev \
            gcc-aarch64-linux-gnu \
            g++-aarch64-linux-gnu \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      - name: Install frontend dependencies
        run: bun install

      - name: Build Tauri App for AMD64
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v${{ github.event.inputs.version }}
          releaseName: "App v${{ github.event.inputs.version }} for Debian"
          releaseBody: "Release for Linux Debian. Download and install the package for your Debian system."
          releaseDraft: false
          prerelease: ${{ github.event.inputs.prerelease }}

      - name: Package for Debian
        run: |
          mkdir -p dist
          # Get system architecture to use in package name
          ARCH=$(dpkg --print-architecture)
          cp src-tauri/target/release/bundle/deb/*.deb dist/app-${{ github.event.inputs.version }}-debian-${ARCH}.deb

          # Check if AppImage directory exists AND if we're not on ARM architecture
          # AppImage creation is skipped on ARM due to issues with linuxdeploy
          if [ -d "src-tauri/target/release/bundle/appimage" ] && [ "$ARCH" != "arm64" ]; then
            if [ -f "src-tauri/target/release/bundle/appimage/*.AppImage" ]; then
              cp src-tauri/target/release/bundle/appimage/*.AppImage dist/app-${{ github.event.inputs.version }}-debian-${ARCH}.AppImage
              echo "AppImage bundle created and copied to dist/"
            else
              echo "No AppImage files found in the bundle directory, skipping..."
            fi
          else
            echo "Skipping AppImage packaging for ARM architecture or missing AppImage directory"
          fi

      - name: Archive AMD64 build
        run: |
          tar -czf tauri-amd64.tar.gz dist src-tauri/target/release/hmi

      - name: Upload AMD64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: tauri-amd64
          path: tauri-amd64.tar.gz

      - name: Build Tauri App for ARM64
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PKG_CONFIG_ALLOW_CROSS: "1"
          PKG_CONFIG_PATH: "/usr/lib/aarch64-linux-gnu/pkgconfig"
          PKG_CONFIG_SYSROOT_DIR: "/"
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: "aarch64-linux-gnu-gcc"
          CC_aarch64_unknown_linux_gnu: "aarch64-linux-gnu-gcc"
          AR_aarch64_unknown_linux_gnu: "aarch64-linux-gnu-ar"
        with:
          tauriScript: cross
          args: "--target aarch64-unknown-linux-gnu"
          useCross: true
          tagName: v${{ github.event.inputs.version }}
          releaseName: "App v${{ github.event.inputs.version }} for Debian"
          releaseBody: "Release for Linux Debian. Download and install the package for your Debian system."
          releaseDraft: false
          prerelease: ${{ github.event.inputs.prerelease }}

      - name: Archive ARM64 build
        run: |
          tar -czf tauri-arm64.tar.gz dist src-tauri/target/aarch64-unknown-linux-gnu/release/hmi

      - name: Upload ARM64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: tauri-arm64
          path: tauri-arm64.tar.gz
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          tag_name: v${{ github.event.inputs.version }}
          draft: false
          prerelease: ${{ github.event.inputs.prerelease }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Prepare Docker repo name
        run: echo "REPO_LOWERCASE=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Download AMD64 artifact
        uses: actions/download-artifact@v4
        with:
          name: tauri-amd64
          path: ./docker-artifacts/amd64

      - name: Download ARM64 artifact
        uses: actions/download-artifact@v4
        with:
          name: tauri-arm64
          path: ./docker-artifacts/arm64

      - name: Build and push multi-arch Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            DEBIAN_VERSION=bookworm
            BUILDKIT_INLINE_CACHE=1
          tags: |
            ghcr.io/${{ env.REPO_LOWERCASE }}/app:latest
            ghcr.io/${{ env.REPO_LOWERCASE }}/app:${{ github.event.inputs.version }}
          cache-from: |
            type=gha
          cache-to: |
            type=gha,mode=max
