name: "Build and Publish"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number for this release"
        required: true
        default: "0.1.0"
      prerelease:
        description: "Is this a prerelease?"
        type: boolean
        default: false

jobs:
  publish-tauri:
    permissions:
      contents: write
      packages: write
    env:
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_MAX_CONNECTIONS: ${{ secrets.POSTGRES_MAX_CONNECTIONS || 5 }}
      VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "ubuntu-22.04"
            targetName: "raspberry-pi-debian12"

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static
          sudo apt-get install -y build-essential curl wget file
          sudo apt-get install -y patchelf
          sudo apt-get install -y dpkg-dev

      - name: Install frontend dependencies
        run: bun install

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build frontend
        run: |
          # Install Tauri CLI
          bun add --dev @tauri-apps/cli

          # Build the frontend
          bun run build

      - name: Create Docker image for cross-compilation
        run: |
          # Create a Dockerfile for cross-compilation
          cat > Dockerfile.cross << EOF
          FROM ubuntu:22.04

          # Set non-interactive mode for apt
          ENV DEBIAN_FRONTEND=noninteractive

          # Install dependencies
          RUN apt-get update && apt-get install -y \
              build-essential \
              curl \
              wget \
              file \
              unzip \
              git \
              pkg-config \
              libssl-dev \
              libgtk-3-dev \
              libwebkit2gtk-4.0-dev \
              libwebkit2gtk-4.1-dev \
              libayatana-appindicator3-dev \
              librsvg2-dev \
              patchelf \
              gcc-aarch64-linux-gnu \
              g++-aarch64-linux-gnu \
              libc6-dev-arm64-cross

          # Install Rust
          RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          ENV PATH="/root/.cargo/bin:${PATH}"

          # Add ARM64 target
          RUN rustup target add aarch64-unknown-linux-gnu

          # Set up Cargo config for cross-compilation
          RUN mkdir -p /root/.cargo && \
              echo '[target.aarch64-unknown-linux-gnu]' > /root/.cargo/config && \
              echo 'linker = "aarch64-linux-gnu-gcc"' >> /root/.cargo/config && \
              echo 'rustflags = ["-C", "link-arg=-march=armv8-a"]' >> /root/.cargo/config

          # Install Node.js and npm
          RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
              apt-get install -y nodejs

          # Install Bun
          RUN curl -fsSL https://bun.sh/install | bash
          ENV PATH="/root/.bun/bin:${PATH}"

          # Set working directory
          WORKDIR /app
          EOF

          # Build the Docker image
          docker build -t tauri-cross-arm64 -f Dockerfile.cross .

      - name: Build Tauri App for ARM64 in Docker
        run: |
          # Run the build in the Docker container
          docker run --rm -v $(pwd):/app tauri-cross-arm64 bash -c "
            cd /app &&
            export PATH=/root/.bun/bin:/root/.cargo/bin:\$PATH &&

            # Install dependencies
            bun install &&

            # Create a simplified version for ARM64
            cd src-tauri &&

            # Create a static build configuration
            mkdir -p .cargo
            cat > .cargo/config.toml << 'EOF'
            [target.aarch64-unknown-linux-gnu]
            linker = \"aarch64-linux-gnu-gcc\"
            rustflags = [\"-C\", \"link-arg=-march=armv8-a\"]

            [env]
            PKG_CONFIG_ALLOW_CROSS = \"1\"
            PKG_CONFIG_PATH = \"/usr/lib/aarch64-linux-gnu/pkgconfig:/usr/share/pkgconfig\"
            PKG_CONFIG_SYSROOT_DIR = \"/\"
            EOF

            # Create a simplified Cargo.toml for ARM64 build
            cp Cargo.toml Cargo.toml.bak &&
            sed -i 's/tauri = { version = \".*\", features = \\[.*\\] }/tauri = { version = \"1.5\", features = [] }/' Cargo.toml &&

            # Build a minimal binary for ARM64
            cargo build --target aarch64-unknown-linux-gnu --release
          "

          # Create dist directory
          mkdir -p dist

          # Copy the binary
          cp src-tauri/target/aarch64-unknown-linux-gnu/release/hmi dist/hmi-${{ github.event.inputs.version }}-${{ matrix.targetName }}

          # Create a simple Debian package
          mkdir -p deb-package/DEBIAN
          mkdir -p deb-package/usr/local/bin

          # Create control file
          cat > deb-package/DEBIAN/control << EOF
          Package: hmi
          Version: ${{ github.event.inputs.version }}
          Section: utils
          Priority: optional
          Architecture: arm64
          Maintainer: HMI Team
          Description: HMI Application for Raspberry Pi
           This package provides the HMI application for Raspberry Pi devices.
          EOF

          # Copy binary to package
          cp src-tauri/target/aarch64-unknown-linux-gnu/release/hmi deb-package/usr/local/bin/

          # Build the Debian package
          dpkg-deb --build deb-package
          mv deb-package.deb dist/hmi-${{ github.event.inputs.version }}-${{ matrix.targetName }}.deb

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          tag_name: v${{ github.event.inputs.version }}
          draft: false
          prerelease: ${{ github.event.inputs.prerelease }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image for Debian 12
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            DEBIAN_VERSION=bookworm
          tags: |
            ghcr.io/${{ github.repository }}/app:latest
            ghcr.io/${{ github.repository }}/app:${{ github.event.inputs.version }}
            ghcr.io/${{ github.repository }}/app:debian12-${{ github.event.inputs.version }}
          platforms: linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
