name: "Build and Publish"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number for this release"
        required: true
        default: "0.1.0"
      prerelease:
        description: "Is this a prerelease?"
        type: boolean
        default: false

jobs:
  publish-tauri:
    permissions:
      contents: write
      packages: write
    env:
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_MAX_CONNECTIONS: ${{ secrets.POSTGRES_MAX_CONNECTIONS || 5 }}
      VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "ubuntu-22.04"
            args: "--target aarch64-unknown-linux-gnu"
            targetName: "raspberry-pi-debian12"

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-gnu

      - name: Install cross-compilation tools for Debian 12 Bookworm
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev libgtk-3-dev patchelf
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
          sudo apt-get install -y qemu-user-static
          # Install pkg-config for cross-compilation
          sudo apt-get install -y pkg-config

          # Add ARM64 architecture and update package lists
          sudo dpkg --add-architecture arm64
          sudo apt-get update

          # Install ARM64 cross-compilation libraries
          sudo apt-get install -y libglib2.0-dev
          sudo apt-get install -y crossbuild-essential-arm64

          # Install specific ARM64 libraries needed for Tauri and glib-sys
          sudo apt-get install -y libgtk-3-dev
          sudo apt-get install -y libglib2.0-dev
          sudo apt-get install -y libatk1.0-dev
          sudo apt-get install -y libcairo2-dev
          sudo apt-get install -y libpango1.0-dev
          sudo apt-get install -y libwebkit2gtk-4.1-dev
          sudo apt-get install -y libappindicator3-dev
          sudo apt-get install -y libasound2-dev
          sudo apt-get install -y libssl-dev

      - name: Set up Cargo config for cross-compilation
        run: |
          mkdir -p ~/.cargo
          cat > ~/.cargo/config << EOF
          [target.aarch64-unknown-linux-gnu]
          linker = "aarch64-linux-gnu-gcc"
          rustflags = ["-C", "link-arg=-march=armv8-a"]

          [env]
          PKG_CONFIG_ALLOW_CROSS = "1"
          PKG_CONFIG = "aarch64-linux-gnu-pkg-config"
          EOF

      - name: Set up pkg-config for cross-compilation
        run: |
          # Create a pkg-config wrapper for cross-compilation
          sudo tee /usr/local/bin/aarch64-linux-gnu-pkg-config > /dev/null << 'EOF'
          #!/bin/bash
          export PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig:/usr/share/pkgconfig
          export PKG_CONFIG_LIBDIR=/usr/lib/aarch64-linux-gnu/pkgconfig:/usr/share/pkgconfig
          export PKG_CONFIG_SYSROOT_DIR=/
          exec pkg-config "$@"
          EOF
          sudo chmod +x /usr/local/bin/aarch64-linux-gnu-pkg-config

          # Set environment variables for cross-compilation
          echo 'PKG_CONFIG_ALLOW_CROSS=1' >> $GITHUB_ENV
          echo 'PKG_CONFIG=aarch64-linux-gnu-pkg-config' >> $GITHUB_ENV

      - name: Install frontend dependencies
        run: bun install

      - name: Build Tauri App for Debian 12 Bookworm
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PKG_CONFIG_ALLOW_CROSS: 1
          PKG_CONFIG: aarch64-linux-gnu-pkg-config
          RUSTFLAGS: "-C link-arg=-march=armv8-a"
        with:
          tagName: v${{ github.event.inputs.version }}
          releaseName: "App v${{ github.event.inputs.version }} for Debian 12"
          releaseBody: "Release for Raspberry Pi devices running Debian 12 (Bookworm). Download and install the package for your Raspberry Pi."
          releaseDraft: false
          prerelease: ${{ github.event.inputs.prerelease }}
          args: ${{ matrix.args }}

      - name: Package for Raspberry Pi (Debian 12)
        run: |
          mkdir -p dist
          cp src-tauri/target/aarch64-unknown-linux-gnu/release/bundle/deb/*.deb dist/app-${{ github.event.inputs.version }}-${{ matrix.targetName }}.deb
          if [ -d "src-tauri/target/aarch64-unknown-linux-gnu/release/bundle/appimage" ]; then
            cp src-tauri/target/aarch64-unknown-linux-gnu/release/bundle/appimage/*.AppImage dist/app-${{ github.event.inputs.version }}-${{ matrix.targetName }}.AppImage
          fi

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          tag_name: v${{ github.event.inputs.version }}
          draft: false
          prerelease: ${{ github.event.inputs.prerelease }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image for Debian 12
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            DEBIAN_VERSION=bookworm
          tags: |
            ghcr.io/${{ github.repository }}/app:latest
            ghcr.io/${{ github.repository }}/app:${{ github.event.inputs.version }}
            ghcr.io/${{ github.repository }}/app:debian12-${{ github.event.inputs.version }}
          platforms: linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
